; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = GoogleCalendar_UniversalDriverCACH_FPC8612

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  https://github.com/mobizt/ESP-Signer.git
  bblanchon/ArduinoJson@^6.21.4
	GxEPD2@>=1.4.5
  https://github.com/nlohmann/json.git
  https://github.com/ricmoo/QRCode.git
  https://github.com/tzapu/WiFiManager.git
  adafruit/Adafruit GFX Library
  bodmer/JPEGDecoder@^1.3.0
  marzogh/SPIMemory

# ------------------------------------------------
# -- Google Calendar
# ------------------------------------------------
#v2 Universal Driver CACH
[env:GoogleCalendar_UniversalDriverCACH_DEPG0750RWF86BF]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/DEPG0750RWF86BF/src
    -D GOOGLECALENDAR_UNIVERSALDRIVERCACH_DEPG0750RWF86BF

[env:GoogleCalendar_UniversalDriverCACH_FPC8612]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/FPC8612/src
    -D GOOGLECALENDAR_UNIVERSALDRIVERCACH_FPC8612

[env:GoogleCalendar_UniversalDriverCACH_gdew075t7]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEW075T7/src
    -D GOOGLECALENDAR_UNIVERSALDRIVERCACH_GDEW075T7

[env:GoogleCalendar_UniversalDriverCACH_gdep073e01]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEP073E01/src
    -D GOOGLECALENDAR_UNIVERSALDRIVERCACH_GDEP073E01


# ------------------------------------------------
# -- Google Calendar
# ------------------------------------------------
#v1 Calendar Driver CACH
[env:GoogleCalendar_v1Driver_fpc8612]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/FPC8612/src
    -D GOOGLECALENDAR_V1DRIVER_FPC8612

[env:GoogleCalendar_v1Driver_gdew075t7]
build_src_filter = 
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEW075T7/src
    -D GOOGLECALENDAR_V1DRIVER_GDEW075T7

[env:GoogleCalendar_v1Driver_gdep073e01]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEP073E01/src
    -D GOOGLECALENDAR_V1DRIVER_GDEP073E01



# ------------------------------------------------
# -- Gallery
# ------------------------------------------------

#v2 Universal Driver CACH
[env:Gallery_UniversalDriverCACH_DEPG0750RWF86BF]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/DEPG0750RWF86BF/src
    -D GALLERY_UNIVERSALDRIVER_CACH_DEPG0750RWF86BF

[env:Gallery_UniversalDriverCACH_fpc8612]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/FPC8612/src
    -D GALLERY_UNIVERSALDRIVER_CACH_FPC8612

[env:Gallery_UniversalDriverCACH_GDEW075T7]
build_src_filter = 
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEW075T7/src
    -D GALLERY_UNIVERSALDRIVER_CACH_GDEW075T7

[env:Gallery_UniversalDriverCACH_GDEP073E01]
build_src_filter = 
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEP073E01/src
    -D GALLERY_UNIVERSALDRIVER_CACH_GDEP073E01

[env:Gallery_UniversalDriverCACH_WAVESHARE_13504]
build_src_filter = 
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/WaveShare_13504/src
    -D GALLERY_UNIVERSALDRIVER_CACH_WAVESHARE_13504
    
#v1 Calendar Driver CACH
[env:Gallery_v1Driver_fpc8612]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/FPC8612/src
    -D GALLERY_V1DRIVER_FPC8612


[env:Gallery_v1Driver_gdew075t7]
build_src_filter = 
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEW075T7/src
    -D GALLERY_V1DRIVER_GDEW075T7


[env:Gallery_v1Driver_gdep073e01]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEP073E01/src
    -D GALLERY_V1DRIVER_GDEP073E01


[env:Gallery_v1Driver_WAVESHARE_13504]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/WaveShare_13504/src
    -D GALLERY_V1DRIVER_WAVESHARE_13504



# ------------------------------------------------
# -- Logger Test / Log aus SPIFFS auslesen
# ------------------------------------------------
[env:Logger_Read]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_src_filter =
    +<logger_test/>