; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = gallery_gdep073e01
#default_envs = gallery_fpc8612

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  https://github.com/mobizt/ESP-Signer.git
  bblanchon/ArduinoJson@^6.21.4
	GxEPD2@>=1.4.5
  https://github.com/nlohmann/json.git
  https://github.com/ricmoo/QRCode.git
  https://github.com/tzapu/WiFiManager.git
  adafruit/Adafruit GFX Library
  bodmer/JPEGDecoder@^1.3.0

[env:calendar_fpc8612]
build_src_filter =
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/FPC8612/src
    -D E_PAPER_CALENDAR_FPC8612

[env:calendar_gdwe075t7]
build_src_filter = 
  +<ePaperCalendar/> -<ePaperGalery/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDWE075T7/src
    -D E_PAPER_CALENDAR_GDWE075T7


[env:gallery_gdep073e01]
build_src_filter =
  +<ePaperGalery/> -<ePaperCalendar/>
build_flags =
    -std=c++11
    -Ilib/ePaper_lib/GDEP073E01/src
    -D E_PAPER_GALLERY_GDEP073E01

